In [1]:
import numpy as np
import pandas as pd

In [3]:
def init_network():#定义初始化的神经网络参数
    network={}#创建一个空字典
    network['W1']=np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
    network['b1']=np.array([0.1,0.2,0.3])
    network['W2']=np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
    network['b2']=np.array([0.1,0.2])
    network['W3']=np.array([[0.1,0.3],[0.2,0.4]])
    network['b3']=np.array([0.1,0.2])
    return network

In [5]:
def sigmoid(x):# the input x is row vector
    return 1/(1+np.exp(-x))
def identity_function(x):
    return x #return itself

In [9]:
def forward(network,x):#需要传入参数 network代表权重和偏置参数的字典 x代表输入层的数据 是一个列向量
    W1,W2,W3=network['W1'],network['W2'],network['W3']
    b1,b2,b3=network['b1'],network['b2'],network['b3']
    a1=np.dot(x,W1)+b1 #x是一个1*2 Matrix, W1 is a 2*3 Matrix, check before you use it! Very important!!
    Z1=sigmoid(a1)# from the input layer to the first hidden neuron layer
    a2=np.dot(Z1,W2)+b2 #Z1 is a 1*3 matrix, W2 is a 3*2 matrix
    Z2=sigmoid(a2)#from the first hidden neuron layer to the second hidden neuron layer
    a3=np.dot(Z2,W3)+b3 #Z2 is a 1*2 matrix and W3 is a 2*2 matrix
    y=identity_function(a3) # from the second hidden neuron layer to the ouput layer
    return y

In [13]:
network=init_network()
x=np.array([1.0,0.5])
y=forward(network,x)
print(y)

[0.31682708 0.69627909]


In [17]:
a=np.array([0.1,3.0,6.0])
exp_a=np.exp(a)
print(exp_a)

[  1.10517092  20.08553692 403.42879349]


In [21]:
sum_exp_a=np.sum(exp_a)
print(sum_exp_a)

424.6195013339984


In [25]:
softmax_a = exp_a/sum_exp_a #some kind of proportion and the sum of the result is 1
print(softmax_a)

[0.00260273 0.04730244 0.95009483]


In [27]:
def softmax(x):
    exp_x=np.exp(x)
    sum_exp_x=np.sum(exp_x)
    softmax_x=exp_x/sum_exp_x
    return softmax_x

In [29]:
#overflow consideration
b=np.array([1000,1010,1020])
y=softmax(b)
print(y)#overflow encounteres

[nan nan nan]


C:\Users\loktsinglong\AppData\Local\Temp\ipykernel_27084\843382947.py:2: RuntimeWarning: overflow encountered in exp
  exp_x=np.exp(x)
C:\Users\loktsinglong\AppData\Local\Temp\ipykernel_27084\843382947.py:4: RuntimeWarning: invalid value encountered in divide
  softmax_x=exp_x/sum_exp_x


In [33]:
b_max=np.argmax(b)
b_new=b-b_max
y_new=softmax(b_new)

C:\Users\loktsinglong\AppData\Local\Temp\ipykernel_27084\843382947.py:2: RuntimeWarning: overflow encountered in exp
  exp_x=np.exp(x)
C:\Users\loktsinglong\AppData\Local\Temp\ipykernel_27084\843382947.py:4: RuntimeWarning: invalid value encountered in divide
  softmax_x=exp_x/sum_exp_x


In [35]:
print(b_new) # all are positive numbers

[ 998 1008 1018]


In [37]:
print(b_max)# mistake！！！！ np.argmax returns the index of the max entry!! not the maximum number

2


In [41]:
# we want to create some nagetive numbers to avoid the overflow problem
b_max=np.max(b)
b_new=b-b_max
y_new=softmax(b_new)
print(y_new) # very small quantity

[2.06106005e-09 4.53978686e-05 9.99954600e-01]


In [43]:
y_sum=np.sum(y_new)
print(y_sum)#actually the sum of these numbers are quite approximate to 1

0.9999999999999999


In [51]:
#mnist project
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
mnist=fetch_openml('mnist_784',version=1)
X,y=mnist['data'],mnist['target']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [53]:
isinstance(mnist,pd.DataFrame)

False

In [55]:
isinstance(mnist,pd.Series)

False

In [57]:
print(type(mnist))

<class 'sklearn.utils._bunch.Bunch'>


In [59]:
print(type(X))

<class 'pandas.core.frame.DataFrame'>


In [61]:
print(type(y))

<class 'pandas.core.series.Series'>


In [63]:
print(type(X_train))

<class 'pandas.core.frame.DataFrame'>


In [69]:
img=X_train.iloc[0] # the type of X_train is DataFrame so you have got to use loc[0]
print(img.shape)
print(type(img))

(784,)
<class 'pandas.core.series.Series'>


In [71]:
img_npar=img.values
print(type(img_npar))# only ndarray can be reshaped

<class 'numpy.ndarray'>


In [73]:
re_img_npar=img_npar.reshape(28,28)
print(re_img_npar.shape)

(28, 28)


In [77]:
from PIL import Image
def img_show(img):
    pil_img=Image.fromarray(np.uint8(img))
    pil_img.show()
img_show(img_npar)

In [79]:
img_show(re_img_npar)

In [81]:
label=y_train[0] # the type of y_train is Series
print(label)

5


In [113]:
import pickle
def init_network():
    with open('sample_weight.pkl','rb') as f: #read_binary, for non text data like pictures and videos
        network=pickle.load(f)
    return network # return value
def predict(network,x):
    W1,W2,W3=network['W1'],network['W2'],network['W3']
    b1,b2,b3=network['b1'],network['b2'],network['b3']
    a1=np.dot(x,W1)+b1
    Z1=sigmoid(a1)
    a2=np.dot(Z1,W2)+b2
    Z2=sigmoid(a2)
    a3=np.dot(Z2,W3)+b3
    y=softmax_new(a3)
    return y

In [85]:
print(type(X_test))

<class 'pandas.core.frame.DataFrame'>


In [87]:
print(type(X_test.iloc[0]))

<class 'pandas.core.series.Series'>


In [89]:
print(type(X_test.iloc[0].values))

<class 'numpy.ndarray'>


In [93]:
npar_X_test_0=X_test.iloc[0].values
print(npar_X_test_0.shape)

(784,)


In [99]:
npar_X_test=X_test.values 
len(npar_X_test)
print(npar_X_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [101]:
len(X_test)

14000

In [111]:
network=init_network()
accuracy_cnt=0
for i in range(len(npar_X_test)):
    y=predict(network,X_test.iloc[i].values)
    p=np.argmax(y)
    if p == y_test[i]:
        accuracy_cnt+=1
print('Accuracy:'+str(float(accuracy_cnt)/len(npar_X_test)))

C:\Users\loktsinglong\AppData\Local\Temp\ipykernel_27084\2055867569.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


KeyError: 0

In [115]:
def softmax_new(x):
    x_max=np.max(x)
    x_new=x-x_max
    exp_x=np.exp(x_new)
    sum_exp_x=np.sum(exp_x)
    return exp_x/sum_exp_x

In [117]:
network=init_network()
accuracy_cnt=0
for i in range(len(npar_X_test)):
    y=predict(network,X_test.iloc[i].values)
    p=np.argmax(y)
    if p == y_test[i]:
        accuracy_cnt+=1
print('Accuracy:'+str(float(accuracy_cnt)/len(npar_X_test)))

C:\Users\loktsinglong\AppData\Local\Temp\ipykernel_27084\2055867569.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


KeyError: 0

In [121]:
''' 
overflow took place in sigmoid function
sigmoid=1/(1+exp(-x)) how could overflow take place?
are there some negative numbers in the input data?
 '''
has_negative=np.any(npar_X_test<0)
print(has_negative)

False


In [123]:
y_test[0]

KeyError: 0

In [125]:
# keyError
print(type(y_test))

<class 'pandas.core.series.Series'>


In [127]:
y_test.iloc[0] #series and dataframe use iloc

'8'

In [133]:
y_test.iloc[13999]

'1'

In [131]:
len(y_test)

14000

In [135]:
# the simplest way is to convert y_test into npar_y_test
npar_y_test=y_test.values
network=init_network()
accuracy_cnt=0
for i in range(len(npar_X_test)):
    y=predict(network,X_test.iloc[i].values)
    p=np.argmax(y)
    if p == npar_y_test[i]:
        accuracy_cnt+=1

print('Accuracy:'+str(float(accuracy_cnt)/len(npar_X_test))) # a wrong accuracy result

C:\Users\loktsinglong\AppData\Local\Temp\ipykernel_27084\2055867569.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


Accuracy:0.0


In [141]:
print(y) # y here means the prediction result of the 14000th picture

[1.86614164e-10 9.99018025e-01 3.77019061e-05 5.27728282e-05
 3.38274137e-07 1.70038733e-05 8.86375506e-06 3.68444305e-06
 8.55754018e-04 5.85599860e-06]


In [143]:
print(p)

1


In [147]:
print(npar_y_test[13999])

1


In [149]:
len(npar_X_test)

14000

In [151]:
print(np.sum(y))

0.9999999999999998


In [153]:
print(accuracy_cnt) # there is a problem here

0


In [193]:
# the simplest way is to convert y_test into npar_y_test
npar_y_test=y_test.values
network=init_network()
accuracy_cnt=0
for i in range(len(npar_X_test)):
    y=predict(network,X_test.iloc[i].values)
    p=np.argmax(y)
    #print(f"Predicted: {p}, Actual: {npar_y_test[i]}"
    if p == npar_y_test[i]:
        accuracy_cnt+=1
        print(f"accuracy_cnt:{accuracy_cnt}")

print('Accuracy:'+str(float(accuracy_cnt)/len(npar_X_test))) # a wrong accuracy result

C:\Users\loktsinglong\AppData\Local\Temp\ipykernel_27084\2055867569.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


Accuracy:0.0


In [167]:
# if p == npar_y_test[i]: is invalid?
# the comparison == failed!!!
print(f'type(p):{type(p)}\ntype(y):{type(npar_y_test[13999])}') # they are of different data types

type(p):<class 'numpy.int64'>
type(y):<class 'str'>


In [173]:
# Solution: Force type conversion
npar_y_test=y_test.values
network=init_network()
accuracy_cnt=0
for i in range(len(npar_X_test)):
    y=predict(network,X_test.iloc[i].values) # the same as: y = predict(network, npar_X_test[i])
    p=np.argmax(y)
    if int(p) == int(npar_y_test[i]):
        accuracy_cnt+=1

print('Accuracy:'+str(float(accuracy_cnt)/len(npar_X_test)))

C:\Users\loktsinglong\AppData\Local\Temp\ipykernel_27084\2055867569.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


Accuracy:0.9240714285714285


In [175]:
print(f'npar_X_test_shape:{npar_X_test.shape}')
print(f'npar_X_test[0]_shape:{npar_X_test[0].shape}')
W1,W2,W3=network['W1'],network['W2'],network['W3']
print(f'W1 shape:{W1.shape}, W2 shape:{W2.shape}, W3 shape:{W3.shape}')

npar_X_test_shape:(14000, 784)
npar_X_test[0]_shape:(784,)
W1 shape:(784, 50), W2 shape:(50, 100), W3 shape:(100, 10)


In [181]:
batch_size = 100 # batch size
accuracy_cnt=0
for i in range(0,len(npar_X_test),batch_size):
    X_batch=npar_X_test[i:i+batch_size]
    y_batch=predict(network,X_batch)
    p=np.argmax(y_batch,axis=1) # axis=1 stands for row direction and axis=0 stands for column direction
    accuracy_cnt += np.sum(int(p)==int(npar_y_test[i:i+batch_size])) # int() operation only works for or only valid for the arrays of length 1
print('Accuracy:'+str(float(accuracy_cnt)/len(npar_X_test)))

C:\Users\loktsinglong\AppData\Local\Temp\ipykernel_27084\2055867569.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


TypeError: only length-1 arrays can be converted to Python scalars

In [189]:
int_y_test = npar_y_test.astype(int) # convert the whole numpy array from string into int, changing the data type
batch_size = 100 # batch size
accuracy_cnt=0
for i in range(0,len(npar_X_test),batch_size):
    X_batch=npar_X_test[i:i+batch_size]
    y_batch=predict(network,X_batch)
    p=np.argmax(y_batch,axis=1) # axis=1 stands for row direction and axis=0 stands for column direction
    accuracy_cnt += np.sum(p==int_y_test[i:i+batch_size]) 
print('Accuracy:'+str(float(accuracy_cnt)/len(npar_X_test)))

C:\Users\loktsinglong\AppData\Local\Temp\ipykernel_27084\2055867569.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


Accuracy:0.9240714285714285


In [187]:
X=np.array([[0.1,0.8,0.1],
           [0.3,0.1,0.6],
           [0.3,0.5,0.2],
           [0.8,0.1,0.1]])
y=np.argmax(X,axis=1) #axis=1 stands for row direction
print(y)

[1 2 1 0]


In [191]:
z=np.argmax(X,axis=0) #axis=0 stands for column direction
print(z)

[3 0 1]


In [195]:
y=np.array([1,2,1,0])
t=np.array([1,2,0,0])
print(y==t)

[ True  True False  True]


In [197]:
np.sum(y==t)

3